apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacetraders-front
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacetraders-front
  template:
    metadata:
      labels:
        app: spacetraders-front
    spec:
      containers:
        - name: bb-site
          image: getting-started
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: spacetraders-front-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: spacetraders-front
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 20278