apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacetraders-front
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacetraders-front
  template:
    metadata:
      labels:
        app: spacetraders-front
    spec:
      containers:
        - name: spacetraders-front
          image: spacetraders-front:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: spacetraders-front-entrypoint
  namespace: default
spec:
  type: NodePort
  ipFamilyPolicy: PreferDualStack
  selector:
    app: spacetraders-front
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 30278